Alter `steps_to_run` in config file or command line
MPAS-Dev/compass pull request #104
Opened 2021-04-30 21:26 UTC by xylar

This merge adds the ability for users to choose which steps in a test case they want to run.  They have 2 options.

First, they can alter the `steps_to_run` config option in the `test_case` section at the very top of the test case's config file:
```
[test_case]
steps_to_run = initial_state full_run restart_run
```
The list of `steps_to_run` can be separated by spaces, commas or both.

Or they can specify which steps to run (or which steps not to run) via the ``--steps`` (or ``--no-steps``) flag to ``compass run``:

```
python -m compass run --steps initial_state full_run
python -m compass run --no-steps restart_run
```
Both of these accomplish the same thing -- skipping the ``restart_run`` step of the test case.

The new capability has been added to the documentation.

closes #80

2021-04-30 21:31 UTC, xylar commented
## Testing

I have run the `nightly` test suite on Ubuntu with gnu, and everything passed and is bit-for-bit with master from earlier today.

I also verified that I could modify the config option `steps_to_run` and only the desired steps ran.  Similarly, I verified that I could both explicitly include steps with the ``--steps`` flag and exclude them with the ``--no-steps`` flag.  I verified that these flags have no effect when calling `compass run` to run a suite or within a step work directory.

2021-04-30 21:32 UTC, xylar commented
@mark-petersen  requested something like this in #80.  This is my suggestion.

@mark-petersen and @matthewhoffman, if you are willing to review, I would appreciate a little testing.  And please let me know if you are happy with this solution or if you have alternative suggestions or changes.

2021-05-10 16:44 UTC, xylar commented
@mark-petersen,

> One of my common workflows is to run the full nightly regression suite once, then rerun it with other compilers or debug, openmp settings, but turn off the QU240 mesh and init to save time. Is there a way to do that? I think this PR does not address omitting a test case from a suite altogether.

My suggestion would be to make version of the nightly suite with and without the test you don't want to run.  I can't think of any way to efficiently specify that you don't want to run a particular step but you could open an issue with a suggested method for doing that.

> I tried it with this functionality, ie
...
with a blank, but it ran that step anyway. The suite function must override the config setting.

Hmm, I can look into that.  If `steps_to_run` isn't getting processed during test-suite runs, that isn't intentional.  I'll get back to you..

2021-05-12 09:47 UTC, xylar commented
@mark-petersen, indeed, `steps_to_run` wasn't getting parsed for test cases run out of a test suite.  I have fixed this now and run the `nightly` suite once with with `mesh` step and once without it, as you suggested.  It worked for me.  Could you verify that it works for you?  

Please also comment on #114 so I can make sure to address your needs there.

2021-05-25 16:17 UTC, matthewhoffman requested changes
@xylar , this looks great.  I added inline comments for the 2 items we discussed on the phone.

2021-05-25 16:17 UTC, matthewhoffman commented on docs/developers_guide/command_line.rst
> +``restart_run`` step of the test case.
Add note that using command line option will override the cfg version.

2021-05-25 16:17 UTC, matthewhoffman commented on compass/run.py
> +        steps_to_run = [step for step in steps_to_run if step not in
Check if step name specified is actually a valid step name or not.  (This should be done for both `--steps` and `--no-steps`.)

2021-05-25 21:35 UTC, xylar commented
@matthewhoffman, thank you for both of your excellent suggestions.  I believe they are now addressed.  Please give this another look when you have a chance.

2021-05-26 16:59 UTC, mark-petersen approved these changes
Looks good. Thanks for these improvements.

2021-06-04 07:08 UTC, xylar commented
@matthewhoffman, still waiting on a re-review here.  Is that something you can do soon?

2021-06-04 16:19 UTC, matthewhoffman commented
I'm looking at this again now.  I got myself confused because I hadnt realized it was rebased on the dev env.

2021-06-04 16:25 UTC, matthewhoffman approved these changes
Looks good @xylar.  Thanks for adding the additional error-checking.  I tried all the ways of asking it to do incorrect things, and it gave sensible errors each time.

2021-06-04 17:38 UTC, xylar commented
Thanks!

2021-06-04 17:38 UTC, merged