Make 'compass list --suites -v' print the contents of a suite
MPAS-Dev/compass pull request #132
Opened 2021-06-08 21:55 UTC by matthewhoffman

This merge also updates the documentation for this change and adds a
short section to the Developer's Guide about developing suites.

2021-06-08 21:55 UTC, pep8speaks commented
Hello @matthewhoffman! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`compass/list.py`](https://github.com/MPAS-Dev/compass/blob/1598b7c4b0fe6027a56cb6bfaf1c213e94662f40/compass/list.py):

> [Line 103:20](https://github.com/MPAS-Dev/compass/blob/1598b7c4b0fe6027a56cb6bfaf1c213e94662f40/compass/list.py#L103): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 103:80](https://github.com/MPAS-Dev/compass/blob/1598b7c4b0fe6027a56cb6bfaf1c213e94662f40/compass/list.py#L103): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 104:20](https://github.com/MPAS-Dev/compass/blob/1598b7c4b0fe6027a56cb6bfaf1c213e94662f40/compass/list.py#L104): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 105:20](https://github.com/MPAS-Dev/compass/blob/1598b7c4b0fe6027a56cb6bfaf1c213e94662f40/compass/list.py#L105): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 106:23](https://github.com/MPAS-Dev/compass/blob/1598b7c4b0fe6027a56cb6bfaf1c213e94662f40/compass/list.py#L106): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 107:23](https://github.com/MPAS-Dev/compass/blob/1598b7c4b0fe6027a56cb6bfaf1c213e94662f40/compass/list.py#L107): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 107:80](https://github.com/MPAS-Dev/compass/blob/1598b7c4b0fe6027a56cb6bfaf1c213e94662f40/compass/list.py#L107): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 108:26](https://github.com/MPAS-Dev/compass/blob/1598b7c4b0fe6027a56cb6bfaf1c213e94662f40/compass/list.py#L108): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four

2021-06-09 06:23 UTC, xylar commented on compass/list.py
> +        When applied to suites, verbose will list the tests in the suite
```suggestion
        when applied to suites, verbose will list the tests in the suite
```

2021-06-09 06:41 UTC, xylar requested changes
This is a really great addition and works like a charm.  I hadn't originally done this because the text files are pretty easy to read but I can definitely see the benefit because they're not that easy to find.  This will be really handy.

I've made a few small suggested edits.  In addition, it would be great if you could take care of the 8 linting issues found above by pep8speaks.  I would like us to stick with the PEP8 style guide pretty strictly.  The main exception are long lines that really can't be broken up without hampering readability, such as very long type names or URLs in doc strings.  Please make sure indentation is always a multiple of 4.  The two long lines pointed out here could be broken into multiple lines as I have suggested below.

2021-06-09 06:41 UTC, xylar commented on compass/list.py
> +        When applied to suites, verbose will list the tests in the suite
```suggestion
        Whether to print details of each test or just the subdirectories.
        When applied to suites, verbose will list the tests in the suite.
```
If you have multiple sentences, the API documentation may put them on the same line (the line breaks here aren't necessarily retained) so it's important to punctuate.

2021-06-09 06:41 UTC, xylar commented on compass/list.py
> +        list_suites(verbose=args.verbose)
Could you update the help string for `--verbose` to also mention suites?

2021-06-09 06:41 UTC, xylar commented on docs/developers_guide/organization.rst
> +desired to be part of the suite.  A line starting with `#` will be treated as a
```suggestion
directory.  The format of the `.txt` file is a list of the work directories of the tests
desired to be part of the suite.  A line starting with `#` will be treated as a
```

2021-06-09 06:41 UTC, xylar commented on compass/list.py
> +                   text = resources.read_text('compass.{}.suites'.format(core), suite)
```suggestion
                   text = resources.read_text('compass.{}.suites'.format(core), 
                                              suite)
```

2021-06-09 06:41 UTC, xylar commented on compass/list.py
> +                         print("\t* {}".format(test))
```suggestion
                      if len(test) > 0 and test not in tests and \
                              not test.startswith('#'):
                          print("\t* {}".format(test))
```

2021-06-09 06:43 UTC, xylar commented
@matthewhoffman, I also really appreciate you taking the initiative to implement this, and not just request this feature.  It makes a really big difference to how the project feels to have others diving into development.

2021-06-09 07:04 UTC, xylar commented on compass/list.py
> +                         print("\t* {}".format(test))
One more thing. I'm not sure why pep8speaks didn't point it out but there need to be 2 blank lines between functions (at line 109).

2021-06-09 17:13 UTC, matthewhoffman commented
@xylar , thanks for reviewing this and providing me feedback on coding style and documentation.  I have flake8 installed now (including a vim plugin), and it really makes linting easy.  (flake8 did identify the missing 2 blank lines after a function, BTW.)  I was aware there were coding standards but I wasn't sure how to easily check my code against them so I kinda ignored it the first time around. :)  I've made all the changes you requested - let me know if you see anything else.

I realized this was a kind of trivial PR to make, functionality-wise, but I had a few reasons to go ahead with it.  The first was I was trying to figure out if I could comment my suite definition .txt files, and this seemed like a nice way to test that.  The second was that I realized that for a user using the released python package, they would not have access to the .txt files (or even for someone working from the repo, they might not be familiar with where to find them).  And then I decided this was a nice simple modification for me to practice making a compass PR!   It's nice to get my feet wet and feel like I can jump into the framework.  With the developer docs and the well-commented source code, it was really easy to figure out how to implement this.

2021-06-09 19:31 UTC, matthewhoffman commented
@xylar , hold of on re-reviewing.  I think some changes are required to support comments in the suite .txt files.  I had tested that yesterday, but I most of have missed something or had a problem with my conda env.

2021-06-09 20:22 UTC, xylar commented
> I think some changes are required to support comments in the suite .txt files.

Yes, I also just tested and all values are parsed, so you are right.  It should be pretty easy to add comment parsing.

2021-06-10 15:03 UTC, matthewhoffman commented
I added a new commit to support test case commenting by the `compass suite` command.  I had previously added it for `compass list` but forgot to also add it to `compass suite`.  

I tested by adding a new line to the landice integaration suite:
```
# foo
```
and I confirmed it was ignored by:
* `compass list --suites -v`
* `compass suite -c landice -t sia_integration -w $scratch4/compass_testing -s -m badger`
* `compass suite -c landice -t sia_integration -w $scratch4/compass_testing --clean -m badger`

The comment line was ignored by all those commands.  This is ready for final review and merge.

2021-06-10 21:17 UTC, xylar approved these changes
@matthewhoffman this looks good.  I think your testing is sufficient.  Feel free to merge when you're ready

2021-06-10 21:30 UTC, merged