Create function to calculate distance to ice edge and grounding line
MPAS-Dev/compass pull request #322
Opened 2022-02-15 22:22 UTC by trhille

Add new function compass.landice.mesh.get_dist_to_edge_and_GL() that calculates the distance from each grid point in gridded dataset to the ice margin and grounding line, which is then passed to compass.landice.mesh.set_cell_width() as input to the cell spacing functions. Add use case for Humboldt.

2022-02-24 18:44 UTC, trhille commented
Force-push from  1e3a14e to 3d8d6d7 was a rebase onto origin/master following merge of PR #321.

2022-02-24 20:10 UTC, xylar commented
@trhille and @matthewhoffman, as a future optimization, you might want to look into faster packages for computing distances such as:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.KDTree.html (used for signed distance functions in MPAS-Tools)

2022-02-24 22:35 UTC, xylar commented
Something went glitchy with testing but I don't think it's an actual problem.  Assuming it eventually times out, I'll rerun it.  Or if there are requested changes, that will trigger it to start again.

2022-02-24 22:43 UTC, xylar approved these changes
Other than my comment that an external package (probably `scikit-fmm`) would almost certainly be much faster, this looks fine to me.

Thanks for generalizing this, @trhille!

2022-02-24 22:48 UTC, trhille commented
Thanks @xylar! I'll address your comment in another PR.

2022-02-25 14:13 UTC, xylar commented
I'm going to re-trigger the testing by closing this and reopening it.  Just so you're not surprised...

2022-02-25 15:28 UTC, matthewhoffman requested changes
@trhille , this generalization looks useful, and I don't see any concerns.  To Xylar's performance comment, I have one small request:  Add a comment at the top of the new routine mentioning the alternate methods that Xylar suggested, and then add a python timer to the function and a log message on how long the function took.  Then we'll have the info we need to improve performance if in practice it becomes limiting.  (But we won't worry about changing the implementation until then.)

2022-02-25 16:20 UTC, trhille commented
@matthewhoffman, thanks for your review. I added a note in the docstring and a log message with the time. It only takes 8 seconds for the Humboldt case. I'm sure that can be improved, but it's certainly not prohibitive for now. But large meshes like the forthcoming Antarctica mesh will probably benefit from @xylar's suggested improvement.

2022-02-25 18:17 UTC, matthewhoffman approved these changes
Thanks, Trevor.  That will be useful.

2022-02-25 18:18 UTC, merged

2022-02-26 04:46 UTC, xylar commented
@trhille, thanks for doing the timing!  It sounds like it's unlikely to become a serious problem.  Get back to me if you need something more efficient down the road.